"""Phase 9: publish the fine-tuned model and the Gradio demo to the Hugging Face Hub.

Usage:
    # add HF_TOKEN=hf_... to .env first (token needs "write" permission)
    python src/publish_hf.py --user <your-hf-username>
    python src/publish_hf.py --user <your-hf-username> --model-only
    python src/publish_hf.py --user <your-hf-username> --space-only

Creates:
    https://huggingface.co/<user>/e5-base-labor-law-ko        (model + model card)
    https://huggingface.co/spaces/<user>/labor-law-retrieval  (Gradio demo)
"""
import argparse
import json
import sys

import yaml
from huggingface_hub import HfApi

from common import ROOT, load_env

sys.stdout.reconfigure(encoding="utf-8", line_buffering=True)

MODEL_REPO = "e5-base-labor-law-ko"
SPACE_REPO = "labor-law-retrieval"

CARD = """---
language: ko
license: mit
base_model: intfloat/multilingual-e5-base
pipeline_tag: sentence-similarity
tags: [sentence-transformers, feature-extraction, sentence-similarity, korean, legal, retrieval]
library_name: sentence-transformers
---

# e5-base-labor-law-ko

`intfloat/multilingual-e5-base` fine-tuned so that **everyday Korean questions about work**
retrieve the **correct statute article or Supreme Court ruling**.

> ⚠️ Portfolio research project, **not legal advice**. 본 모델은 법률 자문을 제공하지 않습니다.

## Why

Korean workers do not ask questions in legal language. Asked
"작년에 안 준 알바비 지금이라도 받을 수 있나요?", BM25 ranked the correct article
(근로기준법 제49조, 임금채권 3년 시효) **3,885th**. This model closes that vocabulary gap.

## Results

{results_table}

335 held-out questions over a 3,922-chunk corpus, 95% bootstrap CIs (1,000 resamples).
The base and fine-tuned Recall@1 intervals do not overlap. A leakage audit
(`check_leakage.py`) gates these numbers and excluded 2 queries whose source ruling is
duplicated upstream under two 판례일련번호.

## Usage

```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("{user}/{repo}")
# keep the e5 prefixes - they were used in training and evaluation
q = model.encode(["query: 5인 미만 사업장도 연차휴가가 있나요?"], normalize_embeddings=True)
p = model.encode(["passage: [근로기준법 제60조(연차 유급휴가)] ..."], normalize_embeddings=True)
print(q @ p.T)
```

## Training

| | |
|---|---|
| Base model | `intfloat/multilingual-e5-base` (MIT) |
| Training pairs | {n_pairs} synthetic question/article pairs |
| Loss | `CachedMultipleNegativesRankingLoss` |
| Batch / mini-batch | {batch} / {mini} |
| Epochs / LR | {epochs} / {lr} |
| Hardware | {gpu}, {peak} GB peak |
| Time | {minutes} minutes |

## Data

11 Korean labor statutes with their decrees and rules, plus 507 Supreme Court rulings (2008+),
from the 법제처 국가법령정보 OpenAPI via the [legalize-kr](https://github.com/legalize-kr/legalize-kr)
mirrors. Statutes and judgments are excluded from copyright under 저작권법 제7조.
**Law snapshot: 2026-09-25** — each statute pinned to the version then in force.

Training questions were generated by free-tier LLMs in the voice of 알바생/정규직/계약직/사장님 and
filtered by rules, near-duplicate detection and an LLM-as-judge answerability check.

## Limitations

- The test set is **LLM-generated and not human-verified**; absolute numbers may be optimistic,
  though the before/after comparison is sound (identical queries for every system).
- Judge coverage was partial (1,626 of 4,102 pairs; it rejected 2.9%).
- 별표 annex tables are missing upstream (PDF only), notably the list of provisions applying to
  workplaces with fewer than 5 employees.
- **Laws change.** Results describe the 2026-09-25 snapshot.
- No forgetting check against a general Korean retrieval benchmark was run.

Full method, decision log and evaluation code:
https://github.com/Habibulo/labor-law-rag-finetune
"""


def results_table():
    m = json.loads((ROOT / "results/phase4_baselines/metrics.json").read_text(encoding="utf-8"))
    rows = ["| System | Recall@1 | Recall@10 | MRR@10 | NDCG@10 |", "|---|---|---|---|---|"]
    for name in [k for k in m if not k.startswith("_")]:
        v, ci = m[name], m[name]["ci95"]
        label = f"**{name}**" if name.startswith("e5-base FINE-TUNED") else name
        rows.append(f"| {label} | {v['recall@1']:.3f} [{ci['recall@1'][0]:.3f}–{ci['recall@1'][1]:.3f}] | "
                    f"{v['recall@10']:.3f} | {v['mrr@10']:.3f} | "
                    f"{v['ndcg@10']:.3f} [{ci['ndcg@10'][0]:.3f}–{ci['ndcg@10'][1]:.3f}] |")
    return "\n".join(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--user", required=True)
    ap.add_argument("--model-only", action="store_true")
    ap.add_argument("--space-only", action="store_true")
    ap.add_argument("--private", action="store_true")
    args = ap.parse_args()

    token = load_env().get("HF_TOKEN")
    if not token:
        sys.exit("HF_TOKEN missing from .env (create one at https://huggingface.co/settings/tokens "
                 "with write permission)")
    api = HfApi(token=token)
    cfg = yaml.safe_load((ROOT / "configs/train_embedding.yaml").read_text(encoding="utf-8"))
    model_dir = ROOT / cfg["output_dir"]

    if not args.space_only:
        if not model_dir.exists():
            sys.exit(f"{model_dir} not found - run src/train_embedding.py first")
        meta = json.loads((ROOT / "results/phase5_embedding/train_meta.json").read_text(encoding="utf-8"))
        repo_id = f"{args.user}/{MODEL_REPO}"
        api.create_repo(repo_id, repo_type="model", exist_ok=True, private=args.private)
        card = CARD.format(user=args.user, repo=MODEL_REPO, results_table=results_table(),
                           n_pairs=meta["n_train_pairs"], batch=cfg["batch_size"],
                           mini=cfg["mini_batch_size"], epochs=cfg["epochs"], lr=cfg["learning_rate"],
                           gpu=meta["gpu"], peak=meta["peak_gpu_memory_gb"], minutes=meta["train_minutes"])
        (model_dir / "README.md").write_text(card, encoding="utf-8")
        print(f"uploading model to {repo_id} ...")
        api.upload_folder(folder_path=str(model_dir), repo_id=repo_id, repo_type="model",
                          ignore_patterns=["_checkpoints/*"])
        print(f"  https://huggingface.co/{repo_id}")

    if not args.model_only:
        repo_id = f"{args.user}/{SPACE_REPO}"
        api.create_repo(repo_id, repo_type="space", space_sdk="gradio", exist_ok=True,
                        private=args.private)
        print(f"uploading Space from app/ to {repo_id} ...")
        api.upload_folder(folder_path=str(ROOT / "app"), repo_id=repo_id, repo_type="space")
        api.add_space_variable(repo_id, "FINETUNED_MODEL", f"{args.user}/{MODEL_REPO}")
        print(f"  https://huggingface.co/spaces/{repo_id}")
        print("  (first build takes a few minutes)")


if __name__ == "__main__":
    main()
